export const Tasks = [
      {
        id: 1,
        title: 'Complete Capstone project',
        description: 'Finish the project before the mentor connect',
        deadline: '2025-07-21',
        priority: 'high',
        completed: true,
      },
      {
        id: 2,
        title: 'Prepare for end',
        description: 'Study slides and notes tomorrow',
        deadline: '2025-06-10',
        priority: 'medium',
        completed: true,
      },
      {
        id: 3,
        title: 'Build Portfolio website',
        description: 'Create a personal portfolio to showcase projects',
        deadline: '2025-12-30',
        priority: 'medium',
        completed: false,
      },
      {
        id: 4,
        title: 'Complete Advanced React course',
        description: 'Finish the last module of the course',
        deadline: '2025-06-10',
        priority: 'high',
        completed: true,
      },
      {
        id: 5, 
        title: 'Prepare for end semester exams',
        description: 'Review all subjects and practice past papers',
        deadline: '2025-08-04',
        priority: 'high',
        completed: false,
      },
      {
        id: 6,
        title: 'Learn Database and Backend',
        description: 'Learn about databases and backend development',
        deadline: '2025-08-04',
        priority: 'low',
        completed: false,
      },
      {
        id: 7,
        title: 'Make backend project',
        description: 'Create a backend project using Node.js and Express',
        deadline: '2025-07-22',
        priority: 'medium',
        completed: false,
      },
      {
        id: 8,
        title: 'Attend workshop on AI',
        description: 'Participate in the AI workshop next week',
        deadline: '2025-07-15',
        priority: 'low',
        completed: true,
      },
      {
        id: 9,
        title: 'Read a book on Web Development',
        description: 'Finish reading "Learning Web Development" by John Doe',
        deadline: '2025-07-30',
        priority: 'medium',
        completed: false,
      },
      {
        id: 10,
        title: 'Join a coding competition',
        description: 'Participate in the upcoming coding competition next month',
        deadline: '2025-08-20',
        priority: 'high',
        completed: false,
      },
      {
        id: 11,
        title: 'Complete Firebase Authentication',
        description: 'Implement email/password authentication and Google sign-in',
        deadline: '2025-07-25',
        priority: 'high',
        completed: true,
      },
      {
        id: 12,
        title: 'Final Capstone Evaluation',
        description: 'Prepare for the final evaluation of the capstone project',
        deadline: '2025-7-21',
        priority: 'high',
        completed: false,
      }
    ];